language: crystal
crystal:
  - latest
install:
  - shards install
script:
  - crystal spec --verbose
  - bin/ameba
before_deploy:
  - crystal docs
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN
  local_dir: docs
  skip_cleanup: true
  keep_history: true
  project_name: inotify.cr
  on:
    tags: true
notifications:
  email:
    on_success: never
    on_failure: always
